### ISSUE TITLE
Unable to transfer to address starting with DDz

### ISSUE THREAD

**Issue by nagarwa2** [bloxbean/cardano-client-lib#13]
Hello, when I am trying to transfer coins to DdzFFzCqrhsswCZ2wF4z3MErJCowrM9VdDB6sdWvj4WLfNZ68yJYZRMpGpAsLLhmVAwuS8jXfor8t2azS4f2PQgbrLP998QhQd8ur3bh it gives me below error

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: JsError { msg: "missing human-readable separator, \"1\"" }', src/address.rs:106:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
com.bloxbean.cardano.client.exception.CborSerializationException: CBOR serialization exception
        at com.bloxbean.cardano.client.transaction.spec.Transaction.serializeToHex(Transaction.java:73)
        at com.bloxbean.cardano.client.backend.api.helper.TransactionHelperService.createSignedTransaction(TransactionHelperService.java:173)
        at com.bloxbean.cardano.client.backend.api.helper.impl.FeeCalculationServiceImpl.calculateFee(FeeCalculationServiceImpl.java:47)
        at com.bloxbean.cardano.client.backend.api.helper.impl.FeeCalculationServiceImpl.calculateFee(FeeCalculationServiceImpl.java:37)
        at com.xyz.wallet.ada.manager.impl.CardanoWalletManager.withdrawFromCompanyWallet(CardanoWalletManager.java:273)
        at com.xyz.wallet.ada.manager.impl.CardanoWalletManager.sendCoinsToAddress(CardanoWalletManager.java:178)
        at com.xyz.wallet.ada.rest.WalletManagerResource.sendCoinsToAddress(WalletManagerResource.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.bloxbean.cardano.client.exception.CborSerializationException: CBOR Serialization failed
        at com.bloxbean.cardano.client.transaction.spec.Transaction.serialize(Transaction.java:64)
        at com.bloxbean.cardano.client.transaction.spec.Transaction.serializeToHex(Transaction.java:70)
        ... 60 more
Caused by: com.bloxbean.cardano.client.exception.AddressExcepion: Address to bytes failed
        at com.bloxbean.cardano.client.account.Account.toBytes(Account.java:188)
        at com.bloxbean.cardano.client.transaction.spec.TransactionOutput.serialize(TransactionOutput.java:26)
        at com.bloxbean.cardano.client.transaction.spec.TransactionBody.serialize(TransactionBody.java:42)
        at com.bloxbean.cardano.client.transaction.spec.Transaction.serialize(Transaction.java:40)
        ... 61 more

Please let me know what I am doing wrong ?

**Comment by satran004** [comment]
Can you try using 0.1.3-beta ? It has support for legacy address.

Similar to https://github.com/bloxbean/cardano-client-lib/issues/8

**Comment by nagarwa2** [comment]
Thank!! it worked like a charm.
