### ISSUE TITLE
NPE in MinAdaCalculator.calculateMinAda when using createFromUtxos(List<Utxo> utxos, String changeAddress) 

### ISSUE THREAD

**Issue by edridudi** [bloxbean/cardano-client-lib#206]
```
java.lang.NullPointerException: Cannot invoke "java.math.BigInteger.multiply(java.math.BigInteger)" because "this.coinsPerUtxoSize" is null
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at com.bloxbean.cardano.client.common.MinAdaCalculator.calculateMinAda(MinAdaCalculator.java:58)
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.math.BigInteger.multiply(java.math.BigInteger)" because "this.coinsPerUtxoSize" is null] with root cause
...
	at com.bloxbean.cardano.client.function.TxBuilderContext.build(TxBuilderContext.java:96)
```

Tx Creation:
```
        UtxoSupplier utxoSupplier = new CIP30UtxoSupplier(utxos);
        Transaction transaction = null;
        TxBuilder txBuilder = output1.outputBuilder().and(createFromMintOutput(mintOutput))
                .buildInputs(createFromUtxos(utxoSupplier.getAll(payerAddress), changeAddress))
                .andThen(mintCreator(policy.getPolicyScript(), multiAsset))
                .andThen(metadataProvider(nftMetadata))
//                .andThen((context, txn) -> txn.getWitnessSet().getNativeScripts().add(policy.getPolicyScript()))
                .andThen((context, txn) -> {
                    txn.getBody().setTtl(detailsParams.getTtl());
                    txn.getBody().setValidityStartInterval(detailsParams.getValidityStartInterval());
                })
                .andThen(balanceTx(changeAddress, 2));

        TxBuilderContext txBuilderContext = TxBuilderContext
                .init(utxoSupplier, cardanoApiService.getProtocolParams(network));
        txBuilderContext.setUtxoSelectionStrategy(new LargestFirstUtxoSelectionStrategy(utxoSupplier));
        try {
            log.info("Building Transaction for Reservation Id: {}" , reservationId);
            transaction = txBuilderContext.build(txBuilder);
        } catch (InsufficientBalanceException e) {
            log.debug("Insufficient Balance for Address: {} Details: {}", payerAddress, e.getMessage());
        }
```

**Comment by edridudi** [comment]
The issue root cause is Koios Returning all null from epoch params endpoint:
https://github.com/cardano-community/koios-artifacts/issues/156
