### ISSUE TITLE
Sending transaction to smart contract deployed on Hydra fails.

### ISSUE THREAD

**Issue by matiwinnetou** [bloxbean/cardano-client-lib#233]
Batch Size: 12

Transacation HEX:
```
84a30081825820eb05ff7ef8a66b0d385ad4c39eed9443bd5a97cfcd7d85b26ba53c7bee4bff6f00018da300581d70080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e011a00111958028201d8185836d8799f5820b9342e2e5a84cc9bf322672a72c5d0c669b4cb8735de2c296428fbd6c8f0ee171a005b480c1a0ee21b221a0003233602ffa300581d70080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e011a00111958028201d8185836d8799f58205aea87ef69f67981b0458cac8b024c330f9b9e37635819fb5ffa24726744a5621a003b7a161a067029331a003b8a5502ffa300581d70080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e011a00111958028201d8185836d8799f582073c6a2aad9dbc10cc5916ad83cd13cbcf74b9ae7564a65bb0a6f3d10e936216c1a0035d3ee1a0ee21b221a003dfe0a00ffa300581d70080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e011a00111958028201d8185836d8799f5820b9342e2e5a84cc9bf322672a72c5d0c669b4cb8735de2c296428fbd6c8f0ee171a005b480c1a0ee21b221a0047b18f02ffa300581d70080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e011a00111958028201d8185836d8799f582032f91ae9d92b48fd15dc578a76ee843abdb96abc46319503fe4a21e774e9934c1a0053c7bc1a0ee21b221a0047b18f00ffa300581d70080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e011a00111958028201d8185836d8799f5820b9342e2e5a84cc9bf322672a72c5d0c669b4cb8735de2c296428fbd6c8f0ee171a005b480c1a0ee21b221a0003233601ffa300581d70080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e011a00111958028201d8185836d8799f58209857ab7d8d13b6b1306afe16dadd5045e87f33d6f26dca0e97e111c6d70f1c0d1a0029905c1a067029331a003b8a5502ffa300581d70080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e011a00111958028201d8185836d8799f582073c6a2aad9dbc10cc5916ad83cd13cbcf74b9ae7564a65bb0a6f3d10e936216c1a0035d3ee1a0ee21b221a000891d200ffa300581d70080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e011a00111958028201d8185836d8799f582032f91ae9d92b48fd15dc578a76ee843abdb96abc46319503fe4a21e774e9934c1a0053c7bc1a0ee21b221a000891d202ffa300581d70080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e011a00111958028201d8185836d8799f5820143b5d0d6f5571effe50cb57d0f6dba7d6e4baf3d50b1adb4d3170fd846b2dc71a003ea09f1a067029331a0049d28002ffa300581d70080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e011a00111958028201d8185836d8799f582032f91ae9d92b48fd15dc578a76ee843abdb96abc46319503fe4a21e774e9934c1a0053c7bc1a0ee21b221a0003233600ffa300581d70080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e011a00111958028201d8185836d8799f5820420ed6c7ece3af5d6c1deb3f977cd62d9de20135f6dfef9ea9a2072704dc10a01a00733edb1a067029331a003b8a5501ff82581d60f8a68cd18e59a6ace848155a0e967af64f4d00cf8acee8adc95a6b0d1b0000001747a66927021a00034eb9a10081825820eb94e8236e2099357fa499bfbc415968691573f25ec77435b7949f5fdfaa5da05840d51b2d071fc6aeced539e89cd588d0c77065cd7cf52caf6d332ca1918212a18576a796712940b4af95f2be867d76820bf04218f4e51dc46f6d5f0773eed3440df5f6
```

and the message is

```

Transaction failed. ApplyTxError [UtxowFailure (UtxoFailure (BabbageOutputTooSmallUTxO [((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X \185\&4..Z\132\204\155\243\"g*r\197\208\198i\180\203\135\&5\222,)d(\251\214\200\240\238\ETB\SUB\NUL[H\f\SUB\SO\226\ESC\"\SUB\NUL\ETX#6\STX\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X Z\234\135\239i\246y\129\176E\140\172\139\STXL3\SI\155\158\&7cX\EM\251_\250$rgD\165b\SUB\NUL;z\SYN\SUB\ACKp)3\SUB\NUL;\138U\STX\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X s\198\162\170\217\219\193\f\197\145j\216<\209<\188\247K\154\231VJe\187\no=\DLE\233\&6!l\SUB\NUL5\211\238\SUB\SO\226\ESC\"\SUB\NUL=\254\n\NUL\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X \185\&4..Z\132\204\155\243\"g*r\197\208\198i\180\203\135\&5\222,)d(\251\214\200\240\238\ETB\SUB\NUL[H\f\SUB\SO\226\ESC\"\SUB\NULG\177\143\STX\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X 2\249\SUB\233\217+H\253\NAK\220W\138v\238\132:\189\185j\188F1\149\ETX\254J!\231t\233\147L\SUB\NULS\199\188\SUB\SO\226\ESC\"\SUB\NULG\177\143\NUL\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X \185\&4..Z\132\204\155\243\"g*r\197\208\198i\180\203\135\&5\222,)d(\251\214\200\240\238\ETB\SUB\NUL[H\f\SUB\SO\226\ESC\"\SUB\NUL\ETX#6\SOH\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X \152W\171}\141\DC3\182\177\&0j\254\SYN\218\221PE\232\DEL3\214\242m\202\SO\151\225\DC1\198\215\SI\FS\r\SUB\NUL)\144\\\SUB\ACKp)3\SUB\NUL;\138U\STX\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X s\198\162\170\217\219\193\f\197\145j\216<\209<\188\247K\154\231VJe\187\no=\DLE\233\&6!l\SUB\NUL5\211\238\SUB\SO\226\ESC\"\SUB\NUL\b\145\210\NUL\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X 2\249\SUB\233\217+H\253\NAK\220W\138v\238\132:\189\185j\188F1\149\ETX\254J!\231t\233\147L\SUB\NULS\199\188\SUB\SO\226\ESC\"\SUB\NUL\b\145\210\STX\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X \DC4;]\roUq\239\254P\203W\208\246\219\167\214\228\186\243\213\v\SUB\219M1p\253\132k-\199\SUB\NUL>\160\159\SUB\ACKp)3\SUB\NULI\210\128\STX\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X 2\249\SUB\233\217+H\253\NAK\220W\138v\238\132:\189\185j\188F1\149\ETX\254J!\231t\233\147L\SUB\NULS\199\188\SUB\SO\226\ESC\"\SUB\NUL\ETX#6\NUL\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X B\SO\214\199\236\227\175]l\GS\235?\151|\214-\157\226\SOH5\246\223\239\158\169\162\a'\EOT\220\DLE\160\SUB\NULs>\219\SUB\ACKp)3\SUB\NUL;\138U\SOH\255",SNothing),Coin 11206000)]))]
java.lang.RuntimeException: Transaction failed. ApplyTxError [UtxowFailure (UtxoFailure (BabbageOutputTooSmallUTxO [((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X \185\&4..Z\132\204\155\243\"g*r\197\208\198i\180\203\135\&5\222,)d(\251\214\200\240\238\ETB\SUB\NUL[H\f\SUB\SO\226\ESC\"\SUB\NUL\ETX#6\STX\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X Z\234\135\239i\246y\129\176E\140\172\139\STXL3\SI\155\158\&7cX\EM\251_\250$rgD\165b\SUB\NUL;z\SYN\SUB\ACKp)3\SUB\NUL;\138U\STX\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X s\198\162\170\217\219\193\f\197\145j\216<\209<\188\247K\154\231VJe\187\no=\DLE\233\&6!l\SUB\NUL5\211\238\SUB\SO\226\ESC\"\SUB\NUL=\254\n\NUL\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X \185\&4..Z\132\204\155\243\"g*r\197\208\198i\180\203\135\&5\222,)d(\251\214\200\240\238\ETB\SUB\NUL[H\f\SUB\SO\226\ESC\"\SUB\NULG\177\143\STX\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X 2\249\SUB\233\217+H\253\NAK\220W\138v\238\132:\189\185j\188F1\149\ETX\254J!\231t\233\147L\SUB\NULS\199\188\SUB\SO\226\ESC\"\SUB\NULG\177\143\NUL\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X \185\&4..Z\132\204\155\243\"g*r\197\208\198i\180\203\135\&5\222,)d(\251\214\200\240\238\ETB\SUB\NUL[H\f\SUB\SO\226\ESC\"\SUB\NUL\ETX#6\SOH\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X \152W\171}\141\DC3\182\177\&0j\254\SYN\218\221PE\232\DEL3\214\242m\202\SO\151\225\DC1\198\215\SI\FS\r\SUB\NUL)\144\\\SUB\ACKp)3\SUB\NUL;\138U\STX\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X s\198\162\170\217\219\193\f\197\145j\216<\209<\188\247K\154\231VJe\187\no=\DLE\233\&6!l\SUB\NUL5\211\238\SUB\SO\226\ESC\"\SUB\NUL\b\145\210\NUL\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X 2\249\SUB\233\217+H\253\NAK\220W\138v\238\132:\189\185j\188F1\149\ETX\254J!\231t\233\147L\SUB\NULS\199\188\SUB\SO\226\ESC\"\SUB\NUL\b\145\210\STX\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X \DC4;]\roUq\239\254P\203W\208\246\219\167\214\228\186\243\213\v\SUB\219M1p\253\132k-\199\SUB\NUL>\160\159\SUB\ACKp)3\SUB\NULI\210\128\STX\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X 2\249\SUB\233\217+H\253\NAK\220W\138v\238\132:\189\185j\188F1\149\ETX\254J!\231t\233\147L\SUB\NULS\199\188\SUB\SO\226\ESC\"\SUB\NUL\ETX#6\NUL\255",SNothing),Coin 11206000),((Addr Testnet (ScriptHashObj (ScriptHash "080a80487a282e59597f49c1cafa2ab0bce31dfe523e599694dfb94e")) StakeRefNull,Value 1120600 (fromList []),Datum "\216y\159X B\SO\214\199\236\227\175]l\GS\235?\151|\214-\157\226\SOH5\246\223\239\158\169\162\a'\EOT\220\DLE\160\SUB\NULs>\219\SUB\ACKp)3\SUB\NUL;\138U\SOH\255",SNothing),Coin 11206000)]))]
	at org.cardanofoundation.hydrapoc.importvote.VoteImporter.createTransactionWithDatum(VoteImporter.java:110)
	at org.cardanofoundation.hydrapoc.importvote.VoteImporter.importVotes(VoteImporter.java:55)
	at org.cardanofoundation.hydrapoc.importvote.VoteImporter$$FastClassBySpringCGLIB$$43861702.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:97)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:133)
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:160)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.cardanofoundation.hydrapoc.importvote.VoteImporter$$EnhancerBySpringCGLIB$$95181cd2.importVotes(<generated>)
	at org.cardanofoundation.hydrapoc.HydraApplicationTests.importVotesFromFile(HydraApplicationTests.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by matiwinnetou** [comment]
Was error on my part.
