### ISSUE TITLE
 KoiosEpochService.getProtocolParameters() method occasionally fails with a parse error

### ISSUE THREAD

**Issue by satran004** [bloxbean/cardano-client-lib#254]
CCL version: 0.5.0-alpha.2

I am getting following error occasionally while accessing KoiosEpochService.getProtocolParameters(). 
To reproduce this error, simply run the test in KoiosEpochServiceTest multiple times.

```
Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.String,java.lang.Long>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"{"PlutusV1": [205665, 812, 1, 1, 1000, 571, 0, 1, 1000, 24177, 4, 1, 1000, 32, 117366, 10475, 4, 23000, 100, 23000, 100, 23000, 100, 23000, 100, 23000, 100, 23000, 100, 100, 100, 23000, 100, 19537, 32, 175354, 32, 46417, 4, 221973, 511, 0, 1, 89141, 32, 497525, 14068, 4, 2, 196500, 453240, 220, 0, 1, 1, 1000, 28662, 4, 2, 245000, 216773, 62, 1, 1060367, 12586, 1, 208512, 421, 1, 187000, 1000, 52998, 1, 80436, 32, 43249, 32, 1000, 32, 80556, 1, 57667, 4, 1000, 10, 197145, 156, 1, 197145, 156, 1, "[truncated 1362 chars]; line: 1, column: 14] (through reference chain: java.util.ArrayList[0]->rest.koios.client.backend.api.epoch.model.EpochParams["cost_models"]->java.util.LinkedHashMap["PlutusV1"])
com.bloxbean.cardano.client.api.exception.ApiException: Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.String,java.lang.Long>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"{"PlutusV1": [205665, 812, 1, 1, 1000, 571, 0, 1, 1000, 24177, 4, 1, 1000, 32, 117366, 10475, 4, 23000, 100, 23000, 100, 23000, 100, 23000, 100, 23000, 100, 23000, 100, 100, 100, 23000, 100, 19537, 32, 175354, 32, 46417, 4, 221973, 511, 0, 1, 89141, 32, 497525, 14068, 4, 2, 196500, 453240, 220, 0, 1, 1, 1000, 28662, 4, 2, 245000, 216773, 62, 1, 1060367, 12586, 1, 208512, 421, 1, 187000, 1000, 52998, 1, 80436, 32, 43249, 32, 1000, 32, 80556, 1, 57667, 4, 1000, 10, 197145, 156, 1, 197145, 156, 1, "[truncated 1362 chars]; line: 1, column: 14] (through reference chain: java.util.ArrayList[0]->rest.koios.client.backend.api.epoch.model.EpochParams["cost_models"]->java.util.LinkedHashMap["PlutusV1"])
	at app//com.bloxbean.cardano.client.backend.koios.KoiosEpochService.getProtocolParameters(KoiosEpochService.java:79)
	at app//com.bloxbean.cardano.client.backend.koios.it.KoiosEpochServiceIT.testGetLatestProtocolParameters(KoiosEpochServiceIT.java:68)
````

**Comment by satran004** [comment]
Fyi. @edridudi

**Comment by edridudi** [comment]
Hi @satran004 ,
I tried a couple of times... issue doesn't seem to reproduce :(

**Comment by satran004** [comment]
Thanks @edridudi . I will check again

**Comment by edridudi** [comment]
@satran004 found the issue.
it is related to the inconsistency of Koios Instances and affects only preprod and preview.

According to Koios Devs:

> It's actually across nodes that were upgraded to 8.x.x nodes ...have upgraded them to Mainnet for now..will see how to best tackle them with a fix before resuming them.
should now show consistent results.

Will keep Monitoring it from my side.

**Comment by satran004** [comment]
Thanks @edridudi. Yes, the issue is still there.

I am not sure, but is it possible to handle both formats in Koios-java based on the response and return the standard object ?

**Comment by edridudi** [comment]
@satran004 ,
Currently, CCL object type is Map<String, Long> (Been Decided so as BF was the first provider to support this).
We can switch it to be JsonNode objectType but it's a breaking Change.
Best way to tackle this is to wait for the next release of Koios and adapt it to the existing model.
Currently for this version there shouldn't be any issues according to Koios Devs.
If there will be any until the next release, then we should open an issue at https://github.com/cardano-community/koios-artifacts repo
